global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-RJON-BUVMQX
      mqDashboard: true
      version: 8.1.0      #updated from 2020.4.1-eus 
      replicas: 2   