global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-CYPF-CRPF3H
      mqDashboard: true
      version: 16.1.2      
      replicas: 2   