apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog-v4-6
  namespace: openshift-marketplace
spec:
  displayName: IBM Operator Catalog 4.6
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog:4.6.14
  updateStrategy:
    registryPoll:
      interval: 45m